// ─── Neighborhoods (top 15 cities, ~15 each) ─────────────────────────────────
export const neighborhoodsByCitySlug: Record<string, Array<{name: string; slug: string; zip: string; note: string}>> = {
  chicago: [
    { name: 'West Loop', slug: 'west-loop', zip: '60661', note: 'Restaurant Row and Fulton Market drive premium valuations. Chicago\'s most competitive SBA acquisition market by buyer-to-listing ratio.' },
    { name: 'Wicker Park', slug: 'wicker-park', zip: '60622', note: 'Creative commercial hub with millennial demographics. Food and retail businesses command strong multiples from an active buyer pool.' },
    { name: 'Logan Square', slug: 'logan-square', zip: '60647', note: 'Chicago\'s most-watched neighborhood for SBA acquisitions. Buyer demand consistently exceeds inventory.' },
    { name: 'River North', slug: 'river-north', zip: '60654', note: 'Chicago\'s hospitality epicenter. Restaurant and nightlife businesses attract experienced operator-buyers.' },
    { name: 'Lincoln Park', slug: 'lincoln-park', zip: '60614', note: 'High-income residential corridor. Service businesses benefit from affluent, consistent customer base.' },
    { name: 'Lakeview', slug: 'lakeview', zip: '60613', note: 'Cubs game traffic and dense residential population create year-round food and bar service demand.' },
    { name: 'Gold Coast', slug: 'gold-coast', zip: '60610', note: 'Chicago\'s highest-income neighborhood. Professional services and luxury businesses command premium valuations.' },
    { name: 'Bucktown', slug: 'bucktown', zip: '60647', note: 'Design-conscious, high-income corridor. Retail and food concepts command above-average SBA multiples.' },
    { name: 'Andersonville', slug: 'andersonville', zip: '60640', note: 'Loyal walkable customer base. Buyers specifically seek community-rooted operations here.' },
    { name: 'Hyde Park', slug: 'hyde-park', zip: '60637', note: 'University of Chicago proximity creates stable academic professional customer base.' },
    { name: 'South Loop', slug: 'south-loop', zip: '60605', note: 'Rapidly growing residential population driving strong service business SBA demand.' },
    { name: 'Pilsen', slug: 'pilsen', zip: '60608', note: 'Culturally vibrant neighborhood attracting creative and food business buyers at accessible price points.' },
    { name: 'Old Town', slug: 'old-town', zip: '60610', note: 'Entertainment-anchored commercial strip with consistently high foot traffic.' },
    { name: 'Streeterville', slug: 'streeterville', zip: '60611', note: 'Northwestern Memorial proximity and Mag Mile tourism create high-traffic mixed-use demand.' },
    { name: 'Naperville', slug: 'naperville', zip: '60540', note: 'Affluent suburban market with high household spending. Strong demand for service business SBA acquisitions.' },
  ],
  'new-york-city': [
    { name: 'Midtown Manhattan', slug: 'midtown-manhattan', zip: '10036', note: 'NYC\'s commercial epicenter. Professional services and B2B businesses command premium SBA multiples.' },
    { name: 'Financial District', slug: 'financial-district', zip: '10005', note: 'Finance industry concentration creates exceptional SBA borrower profiles and lender competition.' },
    { name: 'Upper East Side', slug: 'upper-east-side', zip: '10021', note: 'Highest-income NYC neighborhood. Dental, medical, and luxury service businesses command top SBA multiples.' },
    { name: 'Williamsburg', slug: 'williamsburg', zip: '11211', note: 'Creative commercial hub with millennial demographics. Food and retail concepts attract competitive SBA buyer interest.' },
    { name: 'DUMBO', slug: 'dumbo', zip: '11201', note: 'Tech and creative industry concentration. IT and marketing businesses command strong SBA acquisition terms.' },
    { name: 'Flushing', slug: 'flushing', zip: '11354', note: 'Dense cultural commercial district with strong community loyalty. Businesses here transfer with customer base intact.' },
    { name: 'Astoria', slug: 'astoria', zip: '11102', note: 'Food and service corridor with strong residential density. Affordable SBA acquisitions relative to Manhattan.' },
    { name: 'Bronx - Fordham', slug: 'fordham', zip: '10458', note: 'Fordham University proximity and dense residential base create consistent service business demand.' },
    { name: 'Staten Island', slug: 'staten-island', zip: '10301', note: 'Suburban character with NYC market access. Service businesses offer better SBA economics than Manhattan.' },
    { name: 'Harlem', slug: 'harlem', zip: '10027', note: 'Cultural revitalization driving new SBA acquisition interest. Value-priced opportunities with strong upside.' },
    { name: 'Chelsea', slug: 'chelsea', zip: '10001', note: 'Art gallery and tech office mix creates premium SBA demand for creative and professional services.' },
    { name: 'Greenwich Village', slug: 'greenwich-village', zip: '10014', note: 'Iconic location drives premium valuations. Established businesses here carry address value buyers price in.' },
    { name: 'SoHo', slug: 'soho', zip: '10013', note: 'Premium retail and hospitality district. Businesses command top-of-market SBA valuations.' },
    { name: 'Upper West Side', slug: 'upper-west-side', zip: '10024', note: 'Columbia University proximity and affluent demographics create consistent professional service demand.' },
    { name: 'Long Island City', slug: 'long-island-city', zip: '11101', note: 'NYC adjacency with Queens economics. Major development continues to drive commercial growth.' },
  ],
  'los-angeles': [
    { name: 'Beverly Hills', slug: 'beverly-hills', zip: '90210', note: 'Ultra-premium SBA market. Business addresses carry brand value that buyers consistently price in.' },
    { name: 'Santa Monica', slug: 'santa-monica', zip: '90401', note: 'Beach proximity and high household income. Wellness and food businesses attract the most competitive SBA lenders.' },
    { name: 'West Hollywood', slug: 'west-hollywood', zip: '90046', note: 'Sunset Strip entertainment district. Nightlife and retail businesses attract experienced operator-buyers.' },
    { name: 'Downtown LA', slug: 'downtown-la', zip: '90012', note: 'Ongoing revitalization creating below-market SBA acquisition opportunities in an improving corridor.' },
    { name: 'Silver Lake', slug: 'silver-lake', zip: '90026', note: 'Creative residential and commercial mix. Mission-aligned buyers target community-embedded businesses.' },
    { name: 'Culver City', slug: 'culver-city', zip: '90232', note: 'Tech and entertainment hub. Amazon and Apple studios drive professional service and food business demand.' },
    { name: 'Pasadena', slug: 'pasadena', zip: '91101', note: 'Caltech and JPL proximity creates well-educated buyer and customer base for technical service acquisitions.' },
    { name: 'Burbank', slug: 'burbank', zip: '91502', note: 'Entertainment industry hub. Production-adjacent service businesses attract specialized buyers.' },
    { name: 'Studio City', slug: 'studio-city', zip: '91604', note: 'Affluent residential with entertainment industry proximity. Food and service businesses command strong multiples.' },
    { name: 'Sherman Oaks', slug: 'sherman-oaks', zip: '91403', note: 'Affluent San Fernando Valley. High household incomes drive consistent professional service demand.' },
    { name: 'Venice', slug: 'venice', zip: '90291', note: 'Beach culture and tech industry mix. Lifestyle and wellness businesses command premium valuations.' },
    { name: 'Koreatown', slug: 'koreatown', zip: '90005', note: 'Dense commercial district with strong community loyalty. Businesses transfer with established customer base intact.' },
    { name: 'Hollywood', slug: 'hollywood', zip: '90028', note: 'Tourism infrastructure drives hospitality and experiential business SBA demand year-round.' },
    { name: 'Echo Park', slug: 'echo-park', zip: '90026', note: 'Gentrifying corridor with value-priced SBA acquisitions and strong upside as demographics improve.' },
    { name: 'Long Beach', slug: 'long-beach-la', zip: '90802', note: 'Port economy creates logistics and distribution SBA acquisition opportunities with documented B2B contracts.' },
  ],
  houston: [
    { name: 'Heights', slug: 'heights', zip: '77008', note: 'Most walkable Houston neighborhood. Food and lifestyle businesses command premium SBA valuations.' },
    { name: 'Montrose', slug: 'montrose', zip: '77006', note: 'Creative and arts district. Eclectic buyer pool with strong neighborhood loyalty.' },
    { name: 'Midtown', slug: 'midtown-houston', zip: '77004', note: 'Young professional density drives strong food and service business SBA demand.' },
    { name: 'River Oaks', slug: 'river-oaks', zip: '77019', note: 'Houston\'s most affluent neighborhood. Professional services and luxury businesses command top multiples.' },
    { name: 'Galleria / Uptown', slug: 'galleria-uptown', zip: '77056', note: 'Major commercial and retail hub. High foot traffic creates strong revenue documentation for SBA buyers.' },
    { name: 'The Woodlands', slug: 'the-woodlands', zip: '77380', note: 'Affluent master-planned community. Corporate headquarters concentration creates well-capitalized buyer pool.' },
    { name: 'Sugar Land', slug: 'sugar-land', zip: '77478', note: 'Affluent Fort Bend suburb. High household incomes and strong school district drive service business demand.' },
    { name: 'Katy', slug: 'katy', zip: '77450', note: 'Rapidly growing west Houston suburb. Population growth creates new acquisition opportunities annually.' },
    { name: 'Pearland', slug: 'pearland', zip: '77581', note: 'One of Texas\'s fastest-growing suburbs. Population surge creates strong service business demand.' },
    { name: 'Medical Center', slug: 'medical-center-houston', zip: '77030', note: 'World\'s largest medical complex. Healthcare-adjacent service businesses command exceptional SBA multiples.' },
    { name: 'East Downtown (EaDo)', slug: 'eado', zip: '77003', note: 'Gentrifying arts and food district. Value-priced SBA acquisitions with strong appreciation potential.' },
    { name: 'Cypress', slug: 'cypress', zip: '77429', note: 'Northwest Houston growth corridor. Consistent population expansion drives service business demand.' },
    { name: 'Spring Branch', slug: 'spring-branch', zip: '77055', note: 'Diverse demographics and affordable commercial real estate create value-priced SBA opportunities.' },
    { name: 'Stafford', slug: 'stafford', zip: '77477', note: 'Tax-friendly city with no municipal property tax. Business owners benefit from Texas\'s low tax environment.' },
    { name: 'Memorial', slug: 'memorial', zip: '77024', note: 'Affluent west Houston. High household incomes create consistent demand for professional and medical services.' },
  ],
  dallas: [
    { name: 'Uptown', slug: 'uptown-dallas', zip: '75219', note: 'Young professional density drives strong food and service business SBA demand.' },
    { name: 'Deep Ellum', slug: 'deep-ellum', zip: '75226', note: 'Arts and entertainment district. Creative businesses attract mission-aligned SBA buyers.' },
    { name: 'Bishop Arts', slug: 'bishop-arts', zip: '75208', note: 'Independent business culture with loyal neighborhood shoppers and low turnover.' },
    { name: 'Preston Hollow', slug: 'preston-hollow', zip: '75230', note: 'Dallas\'s most affluent neighborhood. Professional services command top SBA multiples.' },
    { name: 'Highland Park', slug: 'highland-park', zip: '75205', note: 'Ultra-affluent enclave. Highest household incomes in Dallas drive premium SBA multiples.' },
    { name: 'Addison', slug: 'addison', zip: '75001', note: 'Restaurant row and office concentration. Food and professional service businesses attract active SBA buyers.' },
    { name: 'Frisco', slug: 'frisco', zip: '75034', note: 'One of the fastest-growing US cities. Population surge creates consistent new service business demand.' },
    { name: 'McKinney', slug: 'mckinney', zip: '75069', note: 'Historic downtown and rapid growth. Value-priced SBA acquisitions with strong upside fundamentals.' },
    { name: 'Allen', slug: 'allen', zip: '75013', note: 'Affluent North Dallas suburb. High household incomes and strong school district drive service demand.' },
    { name: 'Richardson', slug: 'richardson', zip: '75080', note: 'Telecom Corridor concentration. IT and tech service businesses command strong SBA multiples.' },
    { name: 'Plano', slug: 'plano-dallas', zip: '75024', note: 'Corporate headquarters belt. Management buyout opportunities with exceptional buyer quality.' },
    { name: 'Lakewood', slug: 'lakewood-dallas', zip: '75214', note: 'Affluent east Dallas. High household incomes create consistent demand for service and food businesses.' },
    { name: 'Oak Lawn', slug: 'oak-lawn', zip: '75219', note: 'Dense mixed-use corridor. Food and service businesses benefit from consistent foot traffic.' },
    { name: 'Irving / Las Colinas', slug: 'las-colinas', zip: '75039', note: 'Major corporate campus concentration. Professional service and food businesses benefit from employee density.' },
    { name: 'Mesquite', slug: 'mesquite', zip: '75149', note: 'Affordable east Dallas suburb. Value-priced SBA acquisitions with strong residential customer base.' },
  ],
  miami: [
    { name: 'Brickell', slug: 'brickell', zip: '33131', note: 'Miami\'s financial district. International buyers and financial services create premium SBA conditions.' },
    { name: 'Wynwood', slug: 'wynwood', zip: '33127', note: 'Arts and food destination. Creative businesses attract national and international buyers.' },
    { name: 'Coral Gables', slug: 'coral-gables', zip: '33134', note: 'Affluent international community. Professional services command strong SBA multiples.' },
    { name: 'Coconut Grove', slug: 'coconut-grove', zip: '33133', note: 'Upscale marina community. Lifestyle and food businesses attract well-capitalized buyers.' },
    { name: 'Miami Beach', slug: 'miami-beach', zip: '33139', note: 'Tourism economy creates strong hospitality and food service SBA demand year-round.' },
    { name: 'Little Havana', slug: 'little-havana', zip: '33135', note: 'Cultural commercial district with strong community loyalty. Businesses transfer with established customer base.' },
    { name: 'Midtown Miami', slug: 'midtown-miami', zip: '33137', note: 'Growing commercial and residential district. New development drives increasing service business demand.' },
    { name: 'Design District', slug: 'design-district', zip: '33137', note: 'Luxury retail and design hub. Businesses benefit from premium demographic profile.' },
    { name: 'Doral', slug: 'doral', zip: '33122', note: 'International business hub. Latin American business community creates unique acquisition dynamics.' },
    { name: 'Hialeah', slug: 'hialeah', zip: '33010', note: 'Dense Hispanic commercial district. Businesses with strong community ties command loyal customer bases.' },
    { name: 'Aventura', slug: 'aventura', zip: '33160', note: 'Affluent mixed-use corridor. International buyers and high household incomes create premium conditions.' },
    { name: 'Hollywood FL', slug: 'hollywood-fl', zip: '33020', note: 'Growing coastal city between Miami and Fort Lauderdale. Value-priced SBA opportunities in an improving market.' },
    { name: 'Pembroke Pines', slug: 'pembroke-pines', zip: '33024', note: 'Large master-planned suburb. Consistent population growth drives service business acquisition demand.' },
    { name: 'Kendall', slug: 'kendall', zip: '33183', note: 'Large suburban market with strong household incomes. Service businesses benefit from stable demographics.' },
    { name: 'North Miami Beach', slug: 'north-miami-beach', zip: '33160', note: 'Diverse coastal community. Affordable acquisition costs with Miami metro market access.' },
  ],
  atlanta: [
    { name: 'Buckhead', slug: 'buckhead', zip: '30305', note: 'Atlanta\'s financial and luxury hub. Professional services and upscale businesses command top SBA multiples.' },
    { name: 'Midtown Atlanta', slug: 'midtown-atlanta', zip: '30308', note: 'Tech and arts district. IT and creative businesses attract competitive SBA lender terms.' },
    { name: 'Virginia-Highland', slug: 'virginia-highland', zip: '30306', note: 'Walkable commercial corridor with loyal neighborhood shoppers and low business turnover.' },
    { name: 'Decatur', slug: 'decatur', zip: '30030', note: 'Progressive independent business culture. Community-embedded acquisitions attract mission-aligned buyers.' },
    { name: 'Inman Park', slug: 'inman-park', zip: '30307', note: 'Food and creative hub. Established concepts attract buyers willing to pay for brand equity.' },
    { name: 'Old Fourth Ward', slug: 'old-fourth-ward', zip: '30312', note: 'Beltline-driven revitalization creating new acquisition opportunities in a rapidly appreciating corridor.' },
    { name: 'Alpharetta', slug: 'alpharetta', zip: '30009', note: 'Tech hub north of Atlanta. IT and professional service businesses command strong SBA multiples.' },
    { name: 'Marietta', slug: 'marietta', zip: '30060', note: 'Historic Cobb County hub. Lockheed Martin proximity drives aerospace-adjacent acquisition opportunities.' },
    { name: 'Sandy Springs', slug: 'sandy-springs', zip: '30328', note: 'Affluent north Atlanta suburb. High household incomes create consistent professional service demand.' },
    { name: 'Duluth', slug: 'duluth', zip: '30096', note: 'Gwinnett County hub with strong Korean-American business community and diverse commercial activity.' },
    { name: 'Peachtree City', slug: 'peachtree-city', zip: '30269', note: 'Affluent master-planned community. High household incomes drive premium service business demand.' },
    { name: 'Brookhaven', slug: 'brookhaven', zip: '30319', note: 'Affluent intown suburb. Corporate headquarters concentration creates well-capitalized buyer pool.' },
    { name: 'Smyrna', slug: 'smyrna', zip: '30080', note: 'Rapidly growing Cobb County suburb. Population surge creates new service business opportunities.' },
    { name: 'Roswell', slug: 'roswell', zip: '30075', note: 'Historic downtown with affluent demographics. Consistent demand for professional and lifestyle services.' },
    { name: 'Johns Creek', slug: 'johns-creek', zip: '30097', note: 'Highly affluent Fulton County suburb. Among the highest household incomes in metro Atlanta.' },
  ],
  phoenix: [
    { name: 'Scottsdale Old Town', slug: 'scottsdale-old-town', zip: '85251', note: 'Luxury tourism and hospitality hub. Established businesses command premium SBA valuations.' },
    { name: 'Tempe / ASU Area', slug: 'tempe-asu', zip: '85281', note: 'ASU proximity creates entrepreneurial buyer pipeline and consistent service business demand.' },
    { name: 'Chandler / Price Corridor', slug: 'chandler-price', zip: '85224', note: 'Semiconductor industry concentration. IT and manufacturing businesses attract specialized buyers.' },
    { name: 'Gilbert', slug: 'gilbert', zip: '85234', note: 'One of Arizona\'s fastest-growing cities. Population surge creates consistent new service demand.' },
    { name: 'Glendale', slug: 'glendale-az', zip: '85301', note: 'Sports venue proximity and diverse demographics. Food and entertainment businesses attract active buyers.' },
    { name: 'Peoria AZ', slug: 'peoria-az', zip: '85345', note: 'Rapidly growing northwest suburb. Consistent population expansion drives service business acquisition demand.' },
    { name: 'Mesa Downtown', slug: 'mesa-downtown', zip: '85201', note: 'Growing arts district adjacent to major manufacturing base. Value-priced SBA opportunities with upside.' },
    { name: 'Paradise Valley', slug: 'paradise-valley', zip: '85253', note: 'Ultra-affluent enclave. Luxury service businesses command exceptional SBA multiples.' },
    { name: 'Fountain Hills', slug: 'fountain-hills', zip: '85268', note: 'Affluent retirement community. Healthcare and luxury service businesses attract well-capitalized buyers.' },
    { name: 'Queen Creek', slug: 'queen-creek', zip: '85142', note: 'Fastest-growing Phoenix suburb. Agricultural and residential growth creating new commercial opportunities.' },
    { name: 'Surprise', slug: 'surprise-az', zip: '85374', note: 'Rapidly growing northwest Phoenix suburb. Baseball spring training drives tourism-adjacent business demand.' },
    { name: 'Goodyear', slug: 'goodyear', zip: '85338', note: 'Fastest-growing West Valley city. Population surge creates strong service business acquisition demand.' },
    { name: 'Cave Creek', slug: 'cave-creek', zip: '85331', note: 'Upscale desert lifestyle community. Luxury and outdoor businesses attract affluent buyers.' },
    { name: 'Litchfield Park', slug: 'litchfield-park', zip: '85340', note: 'Affluent planned community. High household incomes drive premium service and healthcare business demand.' },
    { name: 'Avondale', slug: 'avondale-az', zip: '85323', note: 'West Valley growth hub. NASCAR track proximity drives tourism and entertainment business demand.' },
  ],
  denver: [
    { name: 'LoDo / Union Station', slug: 'lodo', zip: '80202', note: 'Denver\'s revitalized urban core. Food and professional service businesses attract the most competitive buyers.' },
    { name: 'RiNo (River North)', slug: 'rino', zip: '80216', note: 'Arts and food destination. Creative businesses attract national buyers seeking Denver market exposure.' },
    { name: 'Cherry Creek', slug: 'cherry-creek', zip: '80206', note: 'Luxury retail and professional hub. Affluent demographics drive premium SBA multiples.' },
    { name: 'Capitol Hill', slug: 'capitol-hill-denver', zip: '80203', note: 'Dense residential and commercial corridor. Diverse business types attract a wide SBA buyer pool.' },
    { name: 'Washington Park', slug: 'washington-park', zip: '80209', note: 'Affluent residential with strong neighborhood commercial. Lifestyle businesses command consistent demand.' },
    { name: 'Highland', slug: 'highland-denver', zip: '80211', note: 'Trendy mixed-use corridor. Food and creative businesses attract mission-aligned buyers.' },
    { name: 'Wheat Ridge', slug: 'wheat-ridge', zip: '80033', note: 'Affordable Denver adjacent. Value-priced acquisitions benefiting from Denver market spill-over.' },
    { name: 'Arvada', slug: 'arvada', zip: '80002', note: 'Growing northwest suburb. Olde Town Arvada creates vibrant independent business corridor.' },
    { name: 'Lakewood', slug: 'lakewood-co', zip: '80226', note: 'Federal Center proximity. Government-adjacent businesses attract buyers with federal contracting experience.' },
    { name: 'Littleton', slug: 'littleton', zip: '80120', note: 'Historic downtown and affluent demographics. Service businesses command premium valuations.' },
    { name: 'Centennial', slug: 'centennial', zip: '80112', note: 'Southeast suburban hub. Corporate park concentration creates strong professional service demand.' },
    { name: 'Parker', slug: 'parker', zip: '80134', note: 'Rapidly growing southeast suburb. Population expansion creates new commercial acquisition opportunities.' },
    { name: 'Englewood', slug: 'englewood-co', zip: '80110', note: 'Tech hub adjacent to Denver proper. IT and professional services attract competitive SBA buyers.' },
    { name: 'Thornton', slug: 'thornton', zip: '80229', note: 'North Denver growth corridor. New residential development driving consistent service business demand.' },
    { name: 'Castle Rock', slug: 'castle-rock', zip: '80104', note: 'Premium south corridor growth. Consistent population expansion drives service business demand.' },
  ],
  seattle: [
    { name: 'Capitol Hill', slug: 'capitol-hill-seattle', zip: '98122', note: 'Tech and creative hub. IT and food businesses attract the most competitive Seattle SBA buyers.' },
    { name: 'Fremont', slug: 'fremont', zip: '98103', note: 'Creative independent business culture. Mission-aligned buyers seek community-embedded acquisitions.' },
    { name: 'Ballard', slug: 'ballard', zip: '98107', note: 'Craft brewing and Scandinavian heritage. Food and beverage businesses attract specialized buyers.' },
    { name: 'South Lake Union', slug: 'south-lake-union', zip: '98109', note: 'Amazon headquarters vicinity. Tech-adjacent service businesses command exceptional SBA multiples.' },
    { name: 'Bellevue Downtown', slug: 'bellevue-downtown', zip: '98004', note: 'Microsoft and tech employer hub. IT and professional service businesses attract premium buyers.' },
    { name: 'Pioneer Square', slug: 'pioneer-square', zip: '98104', note: 'Historic arts district. Creative and food businesses attract buyers seeking Seattle\'s original commercial core.' },
    { name: 'Greenwood', slug: 'greenwood', zip: '98103', note: 'Dense north Seattle corridor. Food and service businesses benefit from strong neighborhood loyalty.' },
    { name: 'University District', slug: 'university-district', zip: '98105', note: 'UW proximity creates consistent service demand and entrepreneurial buyer pipeline.' },
    { name: 'Queen Anne', slug: 'queen-anne', zip: '98109', note: 'Affluent residential with Seattle Center proximity. Lifestyle businesses attract well-capitalized buyers.' },
    { name: 'Kirkland', slug: 'kirkland', zip: '98033', note: 'Affluent east side. Google campus and tech presence drive IT service acquisition demand.' },
    { name: 'Redmond', slug: 'redmond', zip: '98052', note: 'Microsoft headquarters. Tech service businesses attract buyers from within the Microsoft ecosystem.' },
    { name: 'Renton', slug: 'renton', zip: '98057', note: 'Boeing proximity creates aerospace-adjacent service business acquisition opportunities.' },
    { name: 'Shoreline', slug: 'shoreline', zip: '98133', note: 'North Seattle suburb with Sound Transit access. Affordable acquisition costs relative to Seattle proper.' },
    { name: 'Burien', slug: 'burien', zip: '98148', note: 'SeaTac Airport adjacent. Logistics and hospitality businesses attract buyers with travel industry experience.' },
    { name: 'Edmonds', slug: 'edmonds', zip: '98020', note: 'Waterfront community with affluent demographics. Lifestyle businesses command premium valuations.' },
  ],
  boston: [
    { name: 'Back Bay', slug: 'back-bay', zip: '02116', note: 'Premium commercial corridor. Professional services and luxury businesses command top SBA multiples.' },
    { name: 'South End', slug: 'south-end', zip: '02118', note: 'Food and creative hub. Established concepts attract buyers willing to pay for brand equity.' },
    { name: 'Fenway / Kenmore', slug: 'fenway-kenmore', zip: '02215', note: 'Red Sox game traffic and university proximity. Food and entertainment businesses attract active buyers.' },
    { name: 'Cambridge', slug: 'cambridge', zip: '02139', note: 'Harvard and MIT proximity creates exceptional buyer and customer quality for technical service acquisitions.' },
    { name: 'Somerville', slug: 'somerville', zip: '02143', note: 'Davis and Union Square revitalization. Creative and food businesses attract mission-aligned buyers.' },
    { name: 'Brookline', slug: 'brookline', zip: '02446', note: 'Affluent residential community. High household incomes drive consistent professional service demand.' },
    { name: 'Watertown', slug: 'watertown', zip: '02472', note: 'Biotech corridor adjacent to Cambridge. Life sciences service businesses attract specialized buyers.' },
    { name: 'Newton', slug: 'newton', zip: '02458', note: 'Affluent west suburb. High household incomes and strong school districts drive premium service demand.' },
    { name: 'Quincy', slug: 'quincy', zip: '02169', note: 'South Shore hub. Affordable acquisition costs relative to Boston proper with T-accessible demographics.' },
    { name: 'Waltham', slug: 'waltham', zip: '02451', note: 'Tech corridor between Boston and 128 belt. IT service businesses attract buyers from across the metro.' },
    { name: 'Burlington MA', slug: 'burlington-ma', zip: '01803', note: 'Route 128 tech corridor. Major mall and office concentration creates strong service business demand.' },
    { name: 'Woburn', slug: 'woburn', zip: '01801', note: 'Industrial and tech hub north of Boston. Distribution and manufacturing acquisitions attract active buyers.' },
    { name: 'Natick', slug: 'natick', zip: '01760', note: 'Affluent Route 9 corridor. Shopper demographics and corporate presence drive professional service demand.' },
    { name: 'Needham', slug: 'needham', zip: '02492', note: 'Affluent Route 128 community. High household incomes drive consistent professional service acquisition demand.' },
    { name: 'Dedham', slug: 'dedham', zip: '02026', note: 'Regional shopping and commercial hub. Accessible acquisition costs relative to inner Boston suburbs.' },
  ],
  nashville: [
    { name: 'East Nashville', slug: 'east-nashville', zip: '37206', note: 'Creative hub with loyal neighborhood shoppers. Food and lifestyle businesses attract mission-aligned buyers.' },
    { name: 'The Gulch', slug: 'the-gulch', zip: '37203', note: 'Luxury mixed-use district. High-income demographics drive premium SBA valuations.' },
    { name: '12 South', slug: '12-south', zip: '37204', note: 'Boutique retail corridor with national brand recognition. Established concepts command premium multiples.' },
    { name: 'Germantown', slug: 'germantown-nashville', zip: '37208', note: 'Revitalized historic district. Upscale food and retail attract buyers seeking Nashville\'s growth story.' },
    { name: 'Green Hills', slug: 'green-hills', zip: '37215', note: 'Affluent south Nashville. High household incomes and Green Hills Mall proximity drive premium demand.' },
    { name: 'Brentwood', slug: 'brentwood', zip: '37027', note: 'Ultra-affluent Williamson County. Highest household incomes in Nashville metro drive premium service demand.' },
    { name: 'Franklin TN', slug: 'franklin-tn', zip: '37064', note: 'Historic downtown with rapid growth. Corporate relocation wave creating strong professional service demand.' },
    { name: 'Murfreesboro', slug: 'murfreesboro', zip: '37130', note: 'MTSU proximity and rapid growth. Value-priced SBA acquisitions in a fast-growing secondary market.' },
    { name: 'Hendersonville', slug: 'hendersonville', zip: '37075', note: 'Affluent north Nashville suburb. Strong school district demographics drive consistent service demand.' },
    { name: 'Clarksville', slug: 'clarksville', zip: '37040', note: 'Fort Campbell adjacent. Military presence creates consistent service business demand and buyer pipeline.' },
    { name: 'Mt. Juliet', slug: 'mt-juliet', zip: '37122', note: 'One of Tennessee\'s fastest-growing cities. Population surge creates strong service business demand.' },
    { name: 'Smyrna TN', slug: 'smyrna-tn', zip: '37167', note: 'Nissan manufacturing hub. Industrial supply chain creates B2B service acquisition opportunities.' },
    { name: 'Nolensville', slug: 'nolensville', zip: '37135', note: 'One of Tennessee\'s fastest-growing communities. New residents creating strong service business demand.' },
    { name: 'Gallatin', slug: 'gallatin', zip: '37066', note: 'Growing Sumner County hub. New residential development creating new commercial acquisition opportunities.' },
    { name: 'Sylvan Park', slug: 'sylvan-park', zip: '37209', note: 'Family-friendly residential corridor. Service businesses benefit from loyal neighborhood customer base.' },
  ],
  'las-vegas': [
    { name: 'The Strip', slug: 'the-strip', zip: '89109', note: 'World\'s most concentrated hospitality market. Established businesses command exceptional SBA premiums.' },
    { name: 'Downtown Las Vegas', slug: 'downtown-las-vegas', zip: '89101', note: 'Fremont Street revitalization creating new acquisition opportunities. Value-priced with strong upside.' },
    { name: 'Summerlin', slug: 'summerlin', zip: '89134', note: 'Affluent master-planned community. High household incomes drive premium professional service demand.' },
    { name: 'Henderson Downtown', slug: 'henderson-downtown', zip: '89002', note: 'Growing suburban hub. Affluent demographics and corporate presence drive service business demand.' },
    { name: 'Green Valley', slug: 'green-valley', zip: '89014', note: 'Established Henderson suburb. Affluent demographics and corporate parks drive service business demand.' },
    { name: 'Spring Valley', slug: 'spring-valley', zip: '89117', note: 'Suburban hub off I-215. Affordable commercial real estate drives strong SBA acquisition economics.' },
    { name: 'Centennial Hills', slug: 'centennial-hills', zip: '89149', note: 'Northwest Las Vegas growth corridor. Consistent population expansion creates new service demand.' },
    { name: 'Enterprise NV', slug: 'enterprise-nv', zip: '89139', note: 'Southwest Las Vegas growth area. New master-planned communities creating consistent service demand.' },
    { name: 'North Las Vegas', slug: 'north-las-vegas', zip: '89030', note: 'Affordable acquisition costs with logistics hub adjacency. Distribution businesses attract active buyers.' },
    { name: 'Paradise', slug: 'paradise-nv', zip: '89109', note: 'Strip-adjacent unincorporated area. Hospitality and service businesses attract experienced operator-buyers.' },
    { name: 'Aliante', slug: 'aliante', zip: '89084', note: 'North Las Vegas master plan. Growing community creating new service business acquisition opportunities.' },
    { name: 'MacDonald Ranch', slug: 'macdonald-ranch', zip: '89012', note: 'Affluent Henderson community. Premium demographics drive strong service and healthcare business demand.' },
    { name: 'Lake Las Vegas', slug: 'lake-las-vegas', zip: '89011', note: 'Luxury resort community. High-net-worth residents create premium service business acquisition demand.' },
    { name: 'Summerlin South', slug: 'summerlin-south', zip: '89135', note: 'Premium planned community. Vegas Golden Knights proximity drives entertainment-adjacent business demand.' },
    { name: 'Whitney Ranch', slug: 'whitney-ranch', zip: '89014', note: 'Affluent Henderson suburb. High household incomes drive consistent professional service demand.' },
  ],
  'san-francisco': [
    { name: 'Mission District', slug: 'mission-district', zip: '94110', note: 'SF\'s most culturally active commercial neighborhood. Loyal local spending and strong community identity.' },
    { name: 'Hayes Valley', slug: 'hayes-valley', zip: '94102', note: 'Boutique retail corridor with some of SF\'s most loyal neighborhood shoppers.' },
    { name: 'Financial District', slug: 'financial-district-sf', zip: '94111', note: 'B2B and professional service demand driven by SF finance and tech sector concentration.' },
    { name: 'Castro', slug: 'castro', zip: '94114', note: 'Strong community identity and loyal customer base. Businesses transfer with established relationships intact.' },
    { name: 'North Beach', slug: 'north-beach', zip: '94133', note: 'Italian heritage and tourism create strong food business demand year-round.' },
    { name: 'Noe Valley', slug: 'noe-valley', zip: '94131', note: 'Affluent family neighborhood. High household incomes drive consistent professional service demand.' },
    { name: 'Pacific Heights', slug: 'pacific-heights', zip: '94115', note: 'SF\'s most affluent residential neighborhood. Luxury service businesses command premium SBA valuations.' },
    { name: 'Richmond District', slug: 'richmond-district', zip: '94118', note: 'Dense mixed demographics. Food businesses benefit from cultural diversity and loyal neighborhood shoppers.' },
    { name: 'SoMa', slug: 'soma', zip: '94103', note: 'Tech hub and nightlife district. IT and entertainment businesses attract competitive buyer interest.' },
    { name: 'Dogpatch', slug: 'dogpatch', zip: '94107', note: 'Industrial arts district with rapid appreciation. Value-priced acquisitions in a fast-improving corridor.' },
    { name: 'Potrero Hill', slug: 'potrero-hill', zip: '94107', note: 'Tech and design hub. IT and creative businesses attract buyers from across the Bay Area.' },
    { name: 'Inner Sunset', slug: 'inner-sunset', zip: '94122', note: 'UCSF medical hub proximity. Healthcare-adjacent businesses attract specialized buyer interest.' },
    { name: 'Outer Sunset', slug: 'outer-sunset', zip: '94116', note: 'Emerging food and culture corridor. Value-priced SBA acquisitions with appreciation potential.' },
    { name: 'Sunset District', slug: 'sunset-district', zip: '94122', note: 'Large residential base. Consistent service demand from stable family demographics.' },
    { name: 'Tenderloin', slug: 'tenderloin', zip: '94102', note: 'Central location with affordable acquisition prices. Value-priced opportunities near major commercial corridors.' },
  ],
}

export type Neighborhood = { name: string; slug: string; zip: string; note: string }
